version: '3'
services:
  mongo:
    image: mongo:7.0.5-jammy
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    networks:
      - raffle-backend-net

networks:
  raffle-backend-net:
    driver: bridge
