server:
  tomcat:
    threads:
      min-spare: 100
      max: 5000

spring:
  application:
    name: raffle-backend-api
  data:
    mongodb:
      database: raffle-db
      uri: mongodb://mongo:mongo@localhost:27017/